### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by debpedrano** [Shouheng88/MarkNote#11]
Hello , I created this new issue because I have a new proposal for you. would you want to see it ? I hope you remember me. Thanks @Shouheng88  !

**Comment by Shouheng88** [comment]
Ok, I'd glad to see :)

**Comment by debpedrano** [comment]
Okay thanks @Shouheng88  !

**Comment by debpedrano** [comment]
Hello, can I update the issue? please response. Thank you :) @Shouheng88

**Comment by Shouheng88** [comment]
Sure ;-)

**Comment by debpedrano** [comment]
@Shouheng88 
if you want some suggestions or maybe your perspective about the design, feel free to tell me.
![image](https://user-images.githubusercontent.com/40510200/46916794-f805d580-cff1-11e8-9aa2-db0cc277e766.png)

**Comment by Shouheng88** [comment]
you can try the material design styled icon ;-)

**Comment by debpedrano** [comment]
okay, i will note that @Shouheng88

**Comment by Shouheng88** [comment]
Hi! @debpedrano, can you design a logo and banner for my another project [CameraX](https://github.com/Shouheng88/CameraX), waiting for your reply:)
