### ISSUE TITLE
App on Google Playstore?

### ISSUE THREAD

**Issue by anishmittal2020** [Shouheng88/MarkNote#12]
Hi! Is this app available on the Google Playstore? If no could you please provide it via Playstore?

**Comment by Shouheng88** [comment]
I rencently don't have much time to do that, but I could provide you with the Apk file if you need it.

**Comment by anishmittal2020** [comment]
Thanks for the response. I found the app at [Mark notes - texture of Markdown notes application (me.shouheng.notepal) - 1.1.6 - Applications - 酷安网](https://www.coolapk.com/apk/178276). Is this what you were referring to? 

I request you to publish it in Playstore as it will be more popular. I found this github repository by chance, it would be more visible if present in the playstore. Also it will not show the annoying message that the file can harm the device when installing apk from another website.

I looked at the procedure which is here: [Upload an app - Play Console Help](https://support.google.com/googleplay/android-developer/answer/113469?hl=en).

Also is the app menu only in Chinese?

**Comment by Shouheng88** [comment]
Thanks for your suggestions. 
1. You can download the APK from that link. That website is also a popular app store in China, so feel free to install the APK.
2. I have just registered a Google developer account days ago, and I will consider to upload the APK to Google Play this weekend. 
3. The app has been translated into three kinds of languages including English, Simplified Chinese and Traditional Chinese.
I hope it can help you.

**Comment by Shouheng88** [comment]
The app is now available at https://play.google.com/store/apps/details?id=me.shouheng.notepal, thanks for your issue :)
