### ISSUE TITLE
目录结构

### ISSUE THREAD

**Issue by longkongjun** [Shouheng88/MarkNote#15]
clone下来不知道怎么编译

**Comment by Shouheng88** [comment]
选择 client 打开，可能需要配置一下 umeng 和 fabric 的 key

**Comment by longkongjun** [comment]
谢谢，已经弄好了

在 2018-12-19 15:01:46，"WngShhng" <notifications@github.com> 写道：


选择 client 打开，可能需要配置一下 umeng 和 fabric 的 key
