### ISSUE TITLE
Dark Theme for Edit Mode

### ISSUE THREAD

**Issue by washere** [Shouheng88/MarkNote#16]
I just discovered this app today. It's a fantastic work. I love it. Congratulations.

The default theme in Edit Mode has a background color which is a type of purple. Can we have:

> Option to change the theme to a standard:

+ **DARK THEME in EDIT MODE**

*THE DAWN* theme would be very nice also for Edit Mode. 

Most coders and professional writers use dark themes to work long hours. 

It would help reduce the strain from our eyes when working long hours typing with this app on Chromebook.

If there is a way to set a dark theme already for edit mode, please tell me. I could not find it in settings or menus.

Thanks again. This app is wonderful.

**Comment by Shouheng88** [comment]
now it support more background colors, will be published soon
