### ISSUE TITLE
请教~

### ISSUE THREAD

**Issue by ylmyg** [Shouheng88/MarkNote#2]
导入项目的时候报错
Program type already present: android.arch.lifecycle.LiveData$LifecycleBoundObserver
Message{kind=ERROR, text=Program type already present: android.arch.lifecycle.LiveData$LifecycleBoundObserver, sources=[Unknown source file], tool name=Optional.of(D8)}
网上找了很多方法，应该是包冲突了，但是还是不能解决，请问作者我该怎么解决

**Comment by Shouheng88** [comment]
这个[答案](https://stackoverflow.com/questions/49056723/errorprogram-type-already-present-android-arch-lifecycle-livedata)能解决你的问题吗？

**Comment by qzqs** [comment]
什么答案？我自己已经解决了，增加lifecycle.LiveData依赖就可以了~
作者这个项目写得不错，学习到了很多东西，感谢~
