### ISSUE TITLE
BUG found in MarkNote The application crashes when I open the application after set the password and click on the three horizontal line

### ISSUE THREAD

**Issue by saraji-ali** [Shouheng88/MarkNote#20]
# Project Information

* Repository: https://github.com/Shouheng88/MarkNote
* Project Name: MarkNote

# Expected behavior
I was expecting that when I put a password on this application and after opening it when I click on the three horizontal lines, All options should be displayed which are available there

# Actual behavior
The application crashes when I open the application after set the password and click on the three horizontal line

# How to reproduce

1-[Download](https://play.google.com/store/apps/details?id=me.shouheng.notepal) the app and open it
2- Go to the application settings and open the security option there and then click Password and set the password on your application.
3-Reopen the application and enter your password
4-And then click on the three horizontal line
5- see bug

* Browser/App version: Current Version 2.0
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190506_133645](https://user-images.githubusercontent.com/50115498/57215844-f65a2a00-6fa2-11e9-83b0-8bfd2061df4e.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>E/AndroidRuntime(15318): FATAL EXCEPTION: main

E/AndroidRuntime(15318): Process: me.shouheng.notepal, PID: 15318

E/AndroidRuntime(15318): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v4.app.Fragment.onOptionsItemSelected(android.view.MenuItem)' on a null object reference

E/AndroidRuntime(15318): 	at me.shouheng.notepal.activity.MainActivity.onOptionsItemSelected(SourceFile:752)

E/AndroidRuntime(15318): 	at android.app.Activity.onMenuItemSelected(Activity.java:3010)

E/AndroidRuntime(15318): 	at android.support.v4.app.e.onMenuItemSelected(SourceFile:436)

E/AndroidRuntime(15318): 	at android.support.v7.app.e.onMenuItemSelected(SourceFile:196)

E/AndroidRuntime(15318): 	at android.support.v7.view.i.onMenuItemSelected(SourceFile:109)

E/AndroidRuntime(15318): 	at android.support.v7.view.i.onMenuItemSelected(SourceFile:109)

E/AndroidRuntime(15318): 	at android.support.v7.widget.bi$1.onClick(SourceFile:188)

E/AndroidRuntime(15318): 	at android.view.View.performClick(View.java:5076)

E/AndroidRuntime(15318): 	at android.view.View$PerformClick.run(View.java:20279)

E/AndroidRuntime(15318): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(15318): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(15318): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(15318): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(15318): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(15318): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(15318): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(15318): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by Shouheng88** [comment]
Thanks for your report, I will handle this issue in few days

**Comment by Shouheng88** [comment]
fixed, thx a lot
