### ISSUE TITLE
键盘没有办法百分百显示到光标一下

### ISSUE THREAD

**Issue by martin-huang** [Shouheng88/MarkNote#23]
键盘没有办法百分百显示到光标一下
参考 纯纯协作的键盘处理看下吧，体验不是很好

**Comment by Shouheng88** [comment]
的确，我们这边要花费很多精力来维护其他的逻辑，这些小细节处理得不好

**Comment by martin-huang** [comment]
这个细节其实比其他功能重要很多，编辑的时候，键盘合光标位置是高频操作

Yan Qing <notifications@github.com> 于2020年2月29日周六 下午4:38写道：

**Comment by Shouheng88** [comment]
以后不会继续使用这种交互了
