### ISSUE TITLE
Trying to connect to OneDrive crashes the app

### ISSUE THREAD

**Issue by Coffeeling** [Shouheng88/MarkNote#25]
As the title says. Trying to connect to OneDrive, MarkNote 2.0 crashes.

**Comment by Shouheng88** [comment]
will be sovled in later version, thanks for your question, any contribution is welcome

**Comment by Coffeeling** [comment]
Okay, I'll check back later then. Really excited to find a markdown app built to be a notetaker and not just a markdown editor (ie. app understands the idea of notebooks)

**Comment by Shouheng88** [comment]
might caused of the apache http library missing classes, solved, try again
