### ISSUE TITLE
Project Enhancement

### ISSUE THREAD

**Issue by debpedrano** [Shouheng88/MarkNote#3]
Good day to you Project Owner

I am a student and a new user in GitHub. I am currently making logo, and with your permission. Can I submit mine for your project  ?

**Comment by debpedrano** [comment]
hello again @Shouheng88 

![image](https://user-images.githubusercontent.com/40510200/41807727-c535c362-7705-11e8-9814-ae3f644e570b.png)

if you want some changes, pls notify me via comment . Thank you

**Comment by debpedrano** [comment]
Or maybe this one.

![image](https://user-images.githubusercontent.com/40510200/41807907-9303e09c-7708-11e8-97a9-c50eb53f9dc3.png)

**Comment by Shouheng88** [comment]
Thanks a lot. It's quite awesome. 
Do you have any idea about changing the background as well? Since I think it's kind of too complicated to include so much element in the same logo.

**Comment by debpedrano** [comment]
What do you mean by the background ? Can you give me some link to directed to the background you mean so that I can make what's best for it. And also, if you like my Logo Design, pls name the sizes you need. I can also make a Banner for your Read Me :) 


-Regards

**Comment by Shouheng88** [comment]
The 'background' means the background of the old logo. I mean you can change the old background as well.

To be honest, I'm not good at designing. The banner is created by a PS template. 
As I said, feel free to contribute to this project. And if you need any PS resources for the current logo and template, don't be hesitate to let me know that, and I will offer my help to you. 

By the way, I recently created a new project [LetsCorp](https://github.com/Shouheng88/LetsCorp) you can also try to design a logo for it if you are interested.

**Comment by debpedrano** [comment]
It would be great to pick light backgrounds, it is more attractive because the main logo of it is on dark color. 

![image](https://user-images.githubusercontent.com/40510200/42008958-d628e1d2-7aba-11e8-82fc-8a5afac78170.png)

**Comment by debpedrano** [comment]
And also there will be no problem in making a design for your another project, just give me the details and your idea , a small idea on how the logo will look like.

**Comment by Shouheng88** [comment]
Thanks for your logos. I think they are very vigorous and I may consider to use the green one in future, since I think it's more good-looking :)

And below is the logo that I want to design for my new project. As you can see, it contains some elements of Chinese Painting. It may be difficult, but you can simplify and make it more material. The building in the logo is important, for the App is designed as a building for people to read some news. 

![lou](https://user-images.githubusercontent.com/15926470/42029100-fb0195f8-7b00-11e8-8e1e-8fb7053edca4.png)

The application is interesting, but compared with that I'm more interested in your new design. 
Wish for your new work and thanks again.

**Comment by debpedrano** [comment]
I will make some logo with that kind of design @Shouheng88

**Comment by debpedrano** [comment]
will you still accept my first logo design ? @Shouheng88

**Comment by debpedrano** [comment]
I am fine on it, maybe I can make logo for the urgent project by tomorrow. but for this one, I can make a PR.

**Comment by Shouheng88** [comment]
Ok, Thanks anyway. You can make a PR, and i will handle it when i have spare time :)

**Comment by debpedrano** [comment]
@Shouheng88 
how about this one ?  this is all I got :D

![image](https://user-images.githubusercontent.com/40510200/42416558-8e8c002e-82a4-11e8-9ce2-54e7a3404b19.png)

**Comment by Shouheng88** [comment]
Excellent! 
This is far more beautiful than i imaged, i really cannot wait to see the effect when using the logo :)
U can make a PR to my another project, and i will handle the.problem left.
I will make u as the contributor for that project, if you don't mind. 
Thanks so much :+1:

**Comment by debpedrano** [comment]
oh my god, thank you for loving it <3

**Comment by debpedrano** [comment]
what are the things you needed @Shouheng88  ? sizes ?

**Comment by Shouheng88** [comment]
you can make two kinds of sizes: 192*192 and 256 * 256 for icon,
and a bigger one used for splash screen, about 300 * 300

**Comment by debpedrano** [comment]
is this fine ? @Shouheng88 
![image](https://user-images.githubusercontent.com/40510200/42514896-0d2579c6-848d-11e8-97ac-6969210af1cd.png)

**Comment by Shouheng88** [comment]
Seems fine, i think it's ok :)

**Comment by debpedrano** [comment]
do you need a Readme Banner ? I will try to make some before I will make a PR on LetsCorp.

**Comment by debpedrano** [comment]
![image](https://user-images.githubusercontent.com/40510200/42725141-62f17590-87b1-11e8-9c81-271b94d8cd8b.png)

**Comment by Shouheng88** [comment]
Hey, I noticed your PR and merged it. I'm very satisfied about your design. it`s cooool! And i will use your logo as soon as posiible :)

**Comment by Shouheng88** [comment]
Hello again, The project is now using the new logo and i maked you as contributor. 
Here is some thing to mention: LetsCorp is an unofficial news client witch may contains politic sensitive news, so it may not be allowed to upload to App Store in China, but it solved my problems and i may upload it to Google Play Store someday. So, never mind, your work was worthy, and i'm very appliciated :)

**Comment by debpedrano** [comment]
@Shouheng88 Thank you so much for the trust :) looking for another project with you.
