### ISSUE TITLE
Compilation error:

### ISSUE THREAD

**Issue by ooyellow58** [Shouheng88/MarkNote#36]
Could not GET 'https://dl.bintray.com/easymark/Android/com/github/lecho/hellocharts-android/v1.5.8/hellocharts-android-v1.5.8.pom'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project

**Comment by Shouheng88** [comment]
Change the hellochars version as this document https://github.com/lecho/hellocharts-android
Perhaps this is because the jcenter is no longer available.

**Comment by Sheldon04** [comment]
thx a lot, but I'm a little bit confused about the usage of 'api + url', because I've changed the hello-charts module link to 'compile + url' and it works. Do you know why·）

**Comment by Shouheng88** [comment]
The 'compile' is same as 'api', and it is the old command to introduce libraires in gradle. See [link](https://stackoverflow.com/questions/44413952/gradle-implementation-vs-api-configuration) for details.
