### ISSUE TITLE
关于电脑端对言叶的建议

### ISSUE THREAD

**Issue by XiaoNNNNNNNN** [Shouheng88/MarkNote#37]
能专门开发一个app嘛。UWP实在是太不稳定了
![KA`LGEB5T43R R%1SV(Z{(I](https://user-images.githubusercontent.com/96342243/182301270-bb36ba46-6d69-4e45-a2c7-7654413e692e.png)

**Comment by dudupoppy** [comment]
在微软商店那下载这个是吗

**Comment by Shouheng88** [comment]
> 能专门开发一个app嘛。UWP实在是太不稳定了 ![KA`LGEB5T43R R%1SV(Z{(I](https://user-images.githubusercontent.com/96342243/182301270-bb36ba46-6d69-4e45-a2c7-7654413e692e.png)

这边建议用 vs code 装一些 md 插件哦
