### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by davidmind** [Shouheng88/MarkNote#4]
Hello, @Shouheng88 am a graphics designer. I want to know, if you want me to create a new logo for your project, i will be creating it for free.

**Comment by Shouheng88** [comment]
Sure go right ahead.

**Comment by davidmind** [comment]
Ok i will go and make a sketch while i get back to you as soon as possible.

**Comment by davidmind** [comment]
Hello @Shouheng88  Here is what i came up with after several sketch, i hope you like it, you can also make suggestion for adjustment and color to be used. 
![mark-note-presentation](https://user-images.githubusercontent.com/37777956/42103250-69c4b938-7bc0-11e8-8a0e-0554994d290b.png)

**Comment by Shouheng88** [comment]
I like the second green one. What do u think about changing the border to shadow?

**Comment by davidmind** [comment]
Ok i will get that done now. Which of the colors did you like?

**Comment by davidmind** [comment]
@WngShhng 
How about this 
![green-marknote](https://user-images.githubusercontent.com/37777956/42126001-9ce8c5da-7c78-11e8-8a54-242c83c837f0.png)


**2nd**


![green-3](https://user-images.githubusercontent.com/37777956/42126098-1381f666-7c7a-11e8-898c-a24534c17105.png)

**Comment by Shouheng88** [comment]
Ok, now i have some suggestions:
1. The BG seems a little dull, can u add some gradient colors or something else?
2. Do u know how to generate icons for Android by Android Studio? The AS will generate shadow for icons automatically. Current shaodw of the icon seems too dark, u can remove the shadow and generate icons by AS.

**Comment by davidmind** [comment]
Hi @Shouheng88 sorry for delay
I have just generate new icon with Android Studio here is a preview of 
xxxhdpi if you are satisfied with the view i will proceed to make a pull request, with other sizes
![marknote launcher](https://user-images.githubusercontent.com/37777956/42192967-f968d1f0-7e63-11e8-8acd-074a58cfd2e5.png)

**Comment by Shouheng88** [comment]
OK, this is good-looking. 
Thanks for your work, now you can make a PR.

**Comment by davidmind** [comment]
@Shouheng88 i have created a pull request this is the link to editable file **[here](https://drive.google.com/folderview?id=1afm-JwIPXvJmaqTruONitnn26HyA4QhX)**

**Comment by Shouheng88** [comment]
Thanks for your PR!
I merged your PR and handled the problem exists, MarkNote is using the new icon now. 👍

**Comment by davidmind** [comment]
Am glad the logo is good enough for the project
